package com.forehapp.store.general.exceptions;

public enum ErrorCode {

    // Auth
    AUTH_EMAIL_ALREADY_REGISTERED,
    AUTH_CODE_ALREADY_USED,
    AUTH_CODE_INVALID,
    AUTH_CODE_EXPIRED,
    AUTH_ACCOUNT_ALREADY_VERIFIED,

    // User
    USER_PASSWORD_INCORRECT,
    USER_PASSWORD_SAME,
    USER_ADDRESS_LIMIT,
    USER_ADDRESS_NOT_FOUND,
    USER_ADDRESS_DEFAULT_DELETE,
    USER_PROFILE_NOT_FOUND,

    // Store
    STORE_ADMIN_REQUIRED,
    STORE_ALREADY_MEMBER,
    STORE_ROLE_SELF_CHANGE,
    STORE_LAST_OWNER,
    STORE_LAST_OWNER_LEAVE,
    STORE_STAFF_CANNOT_REMOVE,
    STORE_MANAGER_REMOVE_RESTRICTED,
    STORE_INSUFFICIENT_PERMISSIONS,
    STORE_ACCESS_DENIED,

    // Product
    PRODUCT_LINE_BRAND_MISMATCH,
    PRODUCT_SKU_DUPLICATE,
    PRODUCT_COMPARE_PRICE_INVALID,
    PRODUCT_ALREADY_ACTIVE,
    PRODUCT_OUT_OF_STOCK,
    PRODUCT_NO_VARIANTS,
    PRODUCT_NO_IMAGES,
    PRODUCT_NO_STOCK_IN_VARIANTS,
    PRODUCT_NOT_DRAFT,
    PRODUCT_ALREADY_INACTIVE,
    PRODUCT_USE_PUBLISH_ENDPOINT,
    PRODUCT_DELETE_REQUIRES_DRAFT,
    PRODUCT_LAST_VARIANT,
    PRODUCT_NOT_FOUND,
    PRODUCT_ATTRIBUTE_VALUE_NOT_FOUND,
    PRODUCT_ATTRIBUTE_ALREADY_LINKED,
    PRODUCT_IMAGE_WRONG_PRODUCT,
    PRODUCT_IMAGE_EMPTY,
    PRODUCT_IMAGE_TOO_LARGE,
    PRODUCT_IMAGE_FORMAT_INVALID,
    PRODUCT_IMAGE_CONTENT_MISMATCH,
    PRODUCT_IMAGE_READ_ERROR,
    PRODUCT_CATALOG_ADMIN_REQUIRED,

    // Inventory
    INVENTORY_QUANTITY_ZERO,
    INVENTORY_SALE_INTERNAL_ONLY,
    INVENTORY_NEGATIVE_ONLY_ADJUSTMENT,
    INVENTORY_ACCESS_DENIED,
    INVENTORY_INSUFFICIENT_STOCK,

    // Cart
    CART_ITEMS_EMPTY,
    CART_ITEM_LIMIT_EXCEEDED,
    CART_VARIANT_REQUIRED,
    CART_VARIANT_NOT_FOUND,
    CART_INSUFFICIENT_STOCK,
    CART_INACTIVE_PRODUCT,
    CART_ACCESS_DENIED,
    CART_NOT_FOUND,
    CART_ITEM_NOT_FOUND,

    // Order
    ORDER_CART_NOT_FOUND,
    ORDER_CART_EMPTY,
    ORDER_ADDRESS_NOT_FOUND,
    ORDER_ADDRESS_STORE_MISMATCH,
    ORDER_ALREADY_PAID,
    ORDER_VARIANT_NOT_FOUND,
    ORDER_INSUFFICIENT_STOCK,
    ORDER_NOT_FOUND,
    ORDER_CUSTOMER_ROLE_REQUIRED,

    // Order group
    ORDER_GROUP_NOT_FOUND,
    ORDER_GROUP_ACCESS_DENIED,
    ORDER_GROUP_INVALID_STATUS,

    // Payment
    PAYMENT_ORDER_NOT_FOUND,
    PAYMENT_ORDER_NOT_PENDING,
    PAYMENT_METHOD_MISMATCH,
    PAYMENT_RECORD_NOT_FOUND,
    PAYMENT_ACCESS_DENIED,
    PAYMENT_GATEWAY_ERROR,

    // Promotion
    COUPON_CODE_DUPLICATE,
    COUPON_DATE_INVALID,
    COUPON_NOT_FOUND,
    COUPON_INVALID,
    COUPON_ACCESS_DENIED,

    // Return
    RETURN_NOT_FOUND,
    RETURN_NOT_APPROVED,
    RETURN_NOT_PENDING,
    RETURN_ORDER_NOT_FOUND,
    RETURN_ORDER_NOT_YOURS,
    RETURN_ORDER_NOT_DELIVERED,
    RETURN_DUPLICATE,
    RETURN_ITEM_NOT_FOUND,
    RETURN_ITEM_QUANTITY_EXCEEDED,
    RETURN_NOT_YOURS,
    RETURN_ACCESS_DENIED,

    // Review
    REVIEW_NOT_FOUND,
    REVIEW_DUPLICATE,
    REVIEW_NOT_PENDING,
    REVIEW_NOT_YOURS,
    REVIEW_APPROVED_DELETE_DENIED,
    REVIEW_ACCESS_DENIED,

    // Wishlist
    WISHLIST_PRODUCT_NOT_FOUND,
    WISHLIST_ITEM_DUPLICATE,
    WISHLIST_LIMIT_EXCEEDED,
    WISHLIST_NOT_FOUND,
    WISHLIST_ITEM_NOT_FOUND,

    // Location
    LOCATION_COUNTRY_NOT_FOUND,
    LOCATION_STATE_NOT_FOUND,
    LOCATION_CITY_NOT_FOUND,

    // Shipping zones
    SHIPPING_ZONE_NOT_FOUND,
    SHIPPING_ZONE_DEFAULT_DUPLICATE,

    // Generic fallbacks
    VALIDATION_ERROR,
    DATA_INTEGRITY_VIOLATION,
    INTERNAL_ERROR
}
